version: "3.9"

services:
  postgres:
    image: postgres:16

    container_name: postgres-grcp

    build: 
      dockerfile: dockerfile

    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
